#!/usr/bin/env perl
use strict;
use warnings;

use FindBin qw($RealBin $RealScript);
use Getopt::Long;

sub usage {
    print <<EOM;
usage: $RealScript 'tweet message'

options:
 --user    set user
 --en      english tweet
EOM
    exit 0;
}

my $HELP;
my $USER;
my $EN;

GetOptions(
    'help'   => \$HELP,
    'user=s' => \$USER,
    'en'     => \$EN,
);

&usage() if $HELP;

if (@ARGV == 0) {
    system("$RealBin/get_access.pl");
    exit 0;
}

my $tweet = $EN ? `$RealBin/concat_orient_en.pl '$ARGV[0]'`
                : `$RealBin/concat_orient_ja.pl '$ARGV[0]'`;

if (defined $USER) {
    system("$RealBin/post.pl --user=$USER '$tweet'");
} else {
    system("$RealBin/post.pl '$tweet'");
}
