#!/usr/bin/env perl
use strict;
use warnings;

use FindBin qw/$Bin/;
use Getopt::Long;

sub usage {
    print <<EOM;
usage: $0              'tweet message'
       $0 --user=user2 'tweet message'
       $0  # add account
EOM
    exit 0;
}

my $HELP;
my $USER;

GetOptions(
    'help'   => \$HELP,
    'user=s' => \$USER,
);

&usage() if $HELP;

if (@ARGV == 0) {
    system("$Bin/get_access.pl");
    exit 0;
}

my $tweet = `$Bin/concat_orient.pl '$ARGV[0]'`;

if (defined $USER) {
    system("$Bin/post.pl --user=$USER '$tweet'");
} else {
    system("$Bin/post.pl '$tweet'");
}
